openapi: 3.0.3
info:
  title: WalletNode REST API
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /artworks/register:
    post:
      tags:
      - artworks
      summary: Registers a new artwork
      description: Registers a new art.
      operationId: artworks#register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
            example:
              artist_name: Leonardo da Vinci
              artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
              artist_website_url: https://www.leonardodavinci.net
              description: The Mona Lisa is an oil painting by Italian artist, inventor,
                and writer Leonardo da Vinci. Likely completed in 1506, the piece
                features a portrait of a seated woman set against an imaginary landscape.
              image_id: d93lsd0
              issued_copies: 5
              keywords: Renaissance, sfumato, portrait
              name: Mona Lisa
              network_fee: 100
              series_name: 'Famous Artist '
              spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
              youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                type: string
                example: Architecto optio odio.
              example: Ipsa quos omnis reprehenderit doloribus.
  /artworks/upload-image:
    post:
      tags:
      - artworks
      summary: Uploads an image
      description: Upload an image that is used when registering the artwork.
      operationId: artworks#uploadImage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadImageRequestBody'
            example:
              file:
              - 77
              - 97
              - 120
              - 105
              - 109
              - 101
              - 32
              - 101
              - 116
              - 46
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Laborum labore nulla veniam atque qui.
              example: Modi nisi eos blanditiis eius.
        "400":
          description: Bad Request response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
              example:
                error:
                  code: 400
                  message: Bad Request
        "500":
          description: Internal Server Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
              example:
                error:
                  code: 500
                  message: Internal Server Error
components:
  schemas:
    BadRequest:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              description: Code refers to a code number in the response header that
                indicates the general classification of the response.
              default: 400
              example: 400
              format: int64
            message:
              type: string
              description: Message is a human-readable explanation specific to this
                occurrence of the problem.
              default: Bad Request
              example: Bad Request
          example:
            code: 400
            message: Bad Request
          required:
          - code
      example:
        error:
          code: 400
          message: Bad Request
      required:
      - error
    RegisterRequestBody:
      type: object
      properties:
        artist_name:
          type: string
          description: Name of the artist
          example: Leonardo da Vinci
          maxLength: 256
        artist_pastelid:
          type: string
          description: Artist's PastelID
          example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          minLength: 86
          maxLength: 86
        artist_website_url:
          type: string
          description: Artist website URL
          example: https://www.leonardodavinci.net
          maxLength: 256
        description:
          type: string
          description: Description of the artwork
          example: The Mona Lisa is an oil painting by Italian artist, inventor, and
            writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          maxLength: 1024
        image_id:
          type: string
          description: Uploaded Image ID
          example: d93lsd0
        issued_copies:
          type: integer
          description: Number of copies issued
          default: 1
          example: 5
          minimum: 1
          maximum: 1000
        keywords:
          type: string
          description: Keywords
          example: Renaissance, sfumato, portrait
          maxLength: 256
        name:
          type: string
          description: Name of the artwork
          example: Mona Lisa
          maxLength: 256
        network_fee:
          type: number
          default: 1
          example: 100
          minimum: 1e-05
        series_name:
          type: string
          description: Series name
          example: 'Famous Artist '
          maxLength: 256
        spendable_address:
          type: string
          description: Spendable address
          example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          minLength: 35
          maxLength: 35
        youtube_url:
          type: string
          description: Artwork creation video youtube URL
          example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
          maxLength: 128
      example:
        artist_name: Leonardo da Vinci
        artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        artist_website_url: https://www.leonardodavinci.net
        description: The Mona Lisa is an oil painting by Italian artist, inventor,
          and writer Leonardo da Vinci. Likely completed in 1506, the piece features
          a portrait of a seated woman set against an imaginary landscape.
        image_id: d93lsd0
        issued_copies: 5
        keywords: Renaissance, sfumato, portrait
        name: Mona Lisa
        network_fee: 100
        series_name: 'Famous Artist '
        spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      required:
      - artist_name
      - name
      - issued_copies
      - image_id
      - artist_pastelid
      - spendable_address
      - network_fee
    UploadImageRequestBody:
      type: object
      properties:
        file:
          type: string
          description: File to upload
          example:
          - 85
          - 116
          - 32
          - 118
          - 101
          - 108
          - 32
          - 101
          - 116
          - 46
          format: binary
      example:
        file:
        - 69
        - 116
        - 32
        - 101
        - 117
        - 109
        - 32
        - 97
        - 117
        - 116
        - 32
        - 105
        - 116
        - 97
        - 113
        - 117
        - 101
        - 46
      required:
      - file
