swagger: "2.0"
info:
  title: WalletNode RESTFull API
  version: "1.0"
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi3.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /tickets:
    get:
      tags:
      - tickets
      summary: list tickets
      description: List all stored tickets.
      operationId: tickets#list
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/TicketsStoredTicketResponseCollection'
      schemes:
      - http
    post:
      tags:
      - tickets
      summary: add tickets
      description: Add a new ticket and return its ID.
      operationId: tickets#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/TicketsAddRequestBody'
          required:
          - first_name
          - last_name
          - ticket
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
definitions:
  StoredTicketResponse:
    title: 'Mediatype identifier: application/vnd.stored-ticket; view=default'
    type: object
    properties:
      address:
        type: string
        description: Address
        example: "614"
        maxLength: 32
      pastel_id:
        type: string
        description: PastelID
        example: "123456789"
        maxLength: 32
      signature:
        type: string
        description: Signature
        example: wdk231r23kkl23rn23jk423nkl.
    description: StoredTicket describes a ticket retrieved by the ticket service.
      (default view)
    example:
      address: t8t
      pastel_id: "123456789"
      signature: wdk231r23kkl23rn23jk423nkl.
    required:
    - address
    - pastel_id
    - signature
  TicketsAddRequestBody:
    title: TicketsAddRequestBody
    type: object
    properties:
      address:
        type: string
        description: Address
        example: h0l
        maxLength: 32
      pastel_id:
        type: string
        description: PastelID
        example: "123456789"
        maxLength: 32
      signature:
        type: string
        description: Signature
        example: wdk231r23kkl23rn23jk423nkl.
    example:
      address: ws8
      pastel_id: "123456789"
      signature: wdk231r23kkl23rn23jk423nkl.
    required:
    - first_name
    - last_name
    - ticket
  TicketsStoredTicketResponseCollection:
    title: 'Mediatype identifier: application/vnd.stored-ticket; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/StoredTicketResponse'
    description: ListResponseBody is the result type for an array of StoredTicketResponse
      (default view)
    example:
    - address: b6t
      pastel_id: "123456789"
      signature: wdk231r23kkl23rn23jk423nkl.
    - address: b6t
      pastel_id: "123456789"
      signature: wdk231r23kkl23rn23jk423nkl.
    - address: b6t
      pastel_id: "123456789"
      signature: wdk231r23kkl23rn23jk423nkl.
    - address: b6t
      pastel_id: "123456789"
      signature: wdk231r23kkl23rn23jk423nkl.
